[package]
name = "lib_xch"
version = "0.10.1"
authors = ["LEXUGE <LEXUGEyky@outlook.com>"]
description = "Crate xch-ceb's official lib"
license = "GPL-3.0"
repository = "https://github.com/XCH-CEB/xch-project"
readme = "README.md"

[badges]
travis-ci = { repository = "XCH-CEB/xch-project" }

[dependencies]
num = "^0.2"
nalgebra = "^0.16"
id_tree = "^1.3"
pest = "^1.0"
pest_derive = "^1.0"
