language: rust

rust:
  - stable

cache: cargo

before_script:
  - rustup component add clippy

script:
  - cargo update
  - cargo build --verbose
  - cargo test --verbose
  - cargo clippy --verbose
  - cargo bench --verbose
