[package]
name = "lib_xch"
version = "0.2.6"
authors = ["LEXUGE <LEXUGEyky@outlook.com>"]
description = "Crate xch-ceb's official lib"
license = "GPL-3.0"
repository = "https://github.com/LEXUGE/lib-xch-ceb"

[dependencies]
lazy_static = "^1.x"
regex = "^0.2"
